name: mxq_karaoke
description: Professional karaoke application for MXQ 4K Pro.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.1
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  wakelock: ^0.6.2
  just_audio: ^0.9.36
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
